<a href="https://colab.research.google.com/github/NULLPX-a/TelecomX_Challenge_Alura_latam/blob/main/TelecomX_challenge_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Telecom X - Análisis de Evasión de Clientes

**Descripcion**

Has sido contratado como asistente de análisis de datos en Telecom X y formarás parte del proyecto "Churn de Clientes". La empresa enfrenta una alta tasa de cancelaciones y necesita comprender los factores que llevan a la pérdida de clientes.

Tu desafío será recopilar, procesar y analizar los datos, utilizando Python y sus principales bibliotecas para extraer información valiosa. A partir de tu análisis, el equipo de Data Science podrá avanzar en modelos predictivos y desarrollar estrategias para reducir la evasión.

# 1. 📌 Extracción

**Descripcion:**

El principal objetivo de esta etapa es Extraer  lsos datos con python disponibles en una API. Estos datos estan en un archivo JSON que contiene la informacion acerca de los clientes.

[Acceso a los datos desde API](https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json)

## 1.1 Importacion de librerias
se importaran las liberias necesarias para la extraccion, manejo y manipulacion de los datos.

- pandas para limpieza y manejo de datos
- numpy para el analisis de los datos
- requests para poder extraer los datos de la api
- json para  analizar, leer, escribir, serializar y deserializar datos en formato JSON

In [1]:
import pandas as pd
import numpy as np
import requests
import json

## 1.2 Extraccion de los datos

En esta sección, realizamos la conexión con la API externa para obtener la información transformarla en un formato manejable.

### Pasos realizados:
1. **Extracción:** Utilizamos la librería `requests` para realizar una petición GET al API.
2. **Carga en Pandas:** Convertimos la respuesta JSON en un `DataFrame` de Pandas.
3. **Limpieza Inicial:** Renombramos columnas y ajustamos los tipos de datos (especialmente fechas y valores numéricos).

In [2]:
url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json'

In [3]:
df = pd.read_json(url)
df

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

## 1.3 Normalizacion de los datos

In [4]:
info_json = requests.get(url)
info_json = info_json.json()
df = pd.json_normalize(info_json)
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

## 1.4 Limpieza de datos

### 1.4.1 Verificacion de datos nulos

In [5]:
df.isnull().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

### 1.4.2 Verificacion de valores duplicados

In [6]:
print(f'Cantidad de duplicados: {df.duplicated().sum()}')

Cantidad de duplicados: 0

### 1.4.3 verificacion de inconsistencias

In [7]:
for col in df.columns:
  print('-----------------------------')
  print(f'Columna: {col} = {df[col].nunique()}')
  print(df[col].unique(),'\n')
  print('-----------------------------\n\n')

-----------------------------
Columna: customerID = 7267
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']

-----------------------------


-----------------------------
Columna: Churn = 3
['No' 'Yes' '']

-----------------------------


-----------------------------
Columna: customer.gender = 2
['Female' 'Male']

-----------------------------


-----------------------------
Columna: customer.SeniorCitizen = 2
[0 1]

-----------------------------


-----------------------------
Columna: customer.Partner = 2
['Yes' 'No']

-----------------------------


-----------------------------
Columna: customer.Dependents = 2
['Yes' 'No']

-----------------------------


-----------------------------
Columna: customer.tenure = 73
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]

-----------------------------


-----------------------------
Columna: phone.PhoneService = 2
['Yes' 'No']

-----------------------------


-----------------------------
Columna: phone.MultipleLines = 3
['No' 'Yes' 'No phone service']

-----------------------------


-----------------------------
Columna: internet.InternetService = 3
['DSL' 'Fiber optic' 'No']

-----------------------------


-----------------------------
Columna: internet.OnlineSecurity = 3
['No' 'Yes' 'No internet service']

-----------------------------


-----------------------------
Columna: internet.OnlineBackup = 3
['Yes' 'No' 'No internet service']

-----------------------------


-----------------------------
Columna: internet.DeviceProtection = 3
['No' 'Yes' 'No internet service']

-----------------------------


-----------------------------
Columna: internet.TechSupport = 3
['Yes' 'No' 'No internet service']

-----------------------------


-----------------------------
Columna: internet.StreamingTV = 3
['Yes' 'No' 'No internet service']

-----------------------------


-----------------------------
Columna: internet.StreamingMovies = 3
['No' 'Yes' 'No internet service']

-----------------------------


-----------------------------
Columna: account.Contract = 3
['One year' 'Month-to-month' 'Two year']

-----------------------------


-----------------------------
Columna: account.PaperlessBilling = 2
['Yes' 'No']

-----------------------------


-----------------------------
Columna: account.PaymentMethod = 4
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

-----------------------------


-----------------------------
Columna: account.Charges.Monthly = 1585
[65.6  59.9  73.9  ... 91.75 68.8  67.85]

-----------------------------


-----------------------------
Columna: account.Charges.Total = 6531
['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

-----------------------------

### 1.4.4 Verificacion de valores en blanco

In [8]:
df.apply(lambda x: x.astype(str).str.strip().isin(['', 'nan'])).sum()

customerID                     0
Churn                        224
customer.gender                0
customer.SeniorCitizen         0
customer.Partner               0
customer.Dependents            0
customer.tenure                0
phone.PhoneService             0
phone.MultipleLines            0
internet.InternetService       0
internet.OnlineSecurity        0
internet.OnlineBackup          0
internet.DeviceProtection      0
internet.TechSupport           0
internet.StreamingTV           0
internet.StreamingMovies       0
account.Contract               0
account.PaperlessBilling       0
account.PaymentMethod          0
account.Charges.Monthly        0
account.Charges.Total         11
dtype: int64

In [9]:
df_vacios = df[df['account.Charges.Total'].astype(str).str.strip() == '']
display(df_vacios)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [10]:
df_vacios = df[df['Churn'].astype(str).str.strip() == '']
display(df_vacios)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
30,0047-ZHDTW,,Female,0,No,No,11,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.3
75,0120-YZLQA,,Male,0,No,No,71,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.1
96,0154-QYHJU,,Male,0,No,No,29,Yes,No,DSL,...,Yes,No,Yes,No,No,One year,Yes,Electronic check,58.75,1696.2
98,0162-RZGMZ,,Female,1,No,No,5,Yes,No,DSL,...,Yes,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.90,287.85
175,0274-VVQOQ,,Male,1,Yes,No,65,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,One year,Yes,Bank transfer (automatic),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7158,9840-GSRFX,,Female,0,No,No,14,Yes,Yes,DSL,...,Yes,No,No,No,No,One year,Yes,Mailed check,54.25,773.2
7180,9872-RZQQB,,Female,0,Yes,No,49,No,No phone service,DSL,...,No,No,No,Yes,No,Month-to-month,No,Bank transfer (automatic),40.65,2070.75
7211,9920-GNDMB,,Male,0,No,No,9,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,76.25,684.85
7239,9955-RVWSC,,Female,0,Yes,Yes,67,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.25,1372.9
7247,9966-VYRTZ,,Female,0,Yes,Yes,31,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,658.95

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

## 2. 🔧 Transformación (T - Transform)

## 2.1 Correccion de inconsistencias

2.1.1 Eliminacion de datos nulos en la columna churn

In [11]:
df = df[df['Churn'].str.strip() != '']
df['Churn'].unique()

print(f'Numero total de filas {df['Churn'].notna().sum()}')

Numero total de filas 7043

### 2.1.2 Correccion de tipos de datos dentro de las columnas

In [13]:
df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'], errors='coerce')

/tmp/ipykernel_70445/2890100959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'], errors='coerce')

In [23]:
print(f'La columna de Cargos totales es de tipo {df['account.Charges.Total'].dtype}')

La columna de Cargos totales es de tipo float64